# Generated by Django 3.2.6 on 2023-08-21 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=300, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('gamma', 'Gamma')], default='alpha', max_length=250, null=True)),
                ('approval_id', models.IntegerField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
