# Generated by Django 3.2.6 on 2023-08-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_authentication', '0004_auto_20230821_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='minimum_approver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
