# Generated by Django 3.2.6 on 2023-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_authentication', '0005_approval_minimum_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapproval',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
